version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./public:/app/public
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    stdin_open: true  # Keep stdin open for React dev server
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production build service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    profiles:
      - production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Test service
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./coverage:/app/coverage  # Mount for test coverage results
      - /app/node_modules
    environment:
      - CI=true
    command: npm test -- --coverage --watchAll=false
    profiles:
      - test