# fly.toml file generated for medio-react-app

app = "medio-react-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  type = "http"
  interval = "15s"
  timeout = "10s"
  grace_period = "5s"
  path = "/"
  protocol = "http"
  tls_skip_verify = false
  headers = {}

[env]
  NODE_ENV = "production"

[[statics]]
  guest_path = "/app/build"
  url_prefix = "/"