# fly.toml app configuration file generated for medio-react-app on 2025-09-13T23:09:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medio-react-app'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  # BACKEND_URL for BFF Proxy - points to backend service
  BACKEND_URL = 'https://medio-backend.fly.dev'
  # REACT_APP_API_URL removed - frontend uses relative URLs in proxy mode

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
