# fly.toml app configuration file generated for medio-backend on 2025-09-17T10:02:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medio-backend'
primary_region = 'iad'

[env]
  NODE_ENV = "production"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
