openapi: 3.0.3
info:
  title: NFC Chip List API
  description: Retrieve all NFC chips registered by the authenticated parent
  version: 1.0.0

paths:
  /api/nfc/chips:
    get:
      summary: Get all registered NFC chips
      description: |
        Retrieves all NFC chips registered by the authenticated parent account.
        Returns chips ordered by creation date (newest first).
      operationId: getNFCChips
      tags:
        - NFC Chips
      security:
        - cookieAuth: []

      responses:
        '200':
          description: List of NFC chips owned by the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NFCChip'
              examples:
                multipleChips:
                  summary: Parent with multiple chips
                  value:
                    - id: "550e8400-e29b-41d4-a716-446655440000"
                      user_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                      chip_uid: "04:5A:B2:C3:D4:E5:F6"
                      label: "Ben's Chip"
                      created_at: "2025-10-19T12:34:56.789Z"
                    - id: "660e8400-e29b-41d4-a716-446655440001"
                      user_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                      chip_uid: "04:7B:C3:D4:E5:F6:08"
                      label: "Lisa's Chip"
                      created_at: "2025-10-19T13:45:12.345Z"
                emptyList:
                  summary: Parent with no chips
                  value: []

        '401':
          description: Unauthorized - missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Authentication required"

        '429':
          description: Too many requests - rate limit exceeded (60 requests per 15 minutes)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'
              example:
                error: "Too many requests"
                retryAfter: "2025-10-19T12:50:00.000Z"

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Failed to fetch NFC chips"

      x-rate-limit:
        limit: 60
        window: 15 minutes
        key: user_id

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
      description: JWT token stored in httpOnly cookie

  schemas:
    NFCChip:
      type: object
      required:
        - id
        - user_id
        - chip_uid
        - label
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique chip record identifier
        user_id:
          type: string
          format: uuid
          description: Parent account that owns the chip
        chip_uid:
          type: string
          description: Normalized NFC chip UID (uppercase hex with colons)
          example: "04:5A:B2:C3:D4:E5:F6"
          pattern: '^[0-9A-F]{2}(:[0-9A-F]{2})+$'
        label:
          type: string
          description: Friendly name assigned by parent
          example: "Ben's Chip"
          minLength: 1
          maxLength: 50
        created_at:
          type: string
          format: date-time
          description: Registration timestamp (ISO 8601)

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Human-readable error message

    RateLimitError:
      type: object
      required:
        - error
        - retryAfter
      properties:
        error:
          type: string
          description: Error message
        retryAfter:
          type: string
          format: date-time
          description: Timestamp when rate limit resets
